### ISSUE TITLE
Wrong call of PermissionGranted Callback

### ISSUE THREAD

**Issue by 4ndro1d** [Euzee/permissionUtil#1]
After granting the permission for the first time, the `onPermissionDenied()` is called. After restarting the app we will end up in `onPermissionGarnted()` directly.

This is the case when trying to retreive permissions for `locationBoth()`, but one of them is not set in the Android Manifest

**Comment by Euzee** [comment]
Thanks, i'll check it on monday.

**Comment by Euzee** [comment]
Hello. Checked your comment.  
There is no problems with library. 

````java 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
````
If you have only fine permissions in manifest and requesting `locationBoth()`, on response system will return that permissions granted only for ACCESS_FINE_LOCATION.

But if you will check next request (even without restart) . 
````java 
ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION)
ActivityCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) 
````
Both are true .
