### ISSUE TITLE
Improvement. ActivityCompat.shouldShowRequestPermissionRationale

### ISSUE THREAD

**Issue by luckcoolla** [Euzee/permissionUtil#3]
When user denies permission by mistake or somehow we have the second attempt to get permission grant(inside our application) - to use Request permission rationale dialog.
Full example and documentation: https://developer.android.com/training/permissions/requesting.html#make-the-request

Can the library be improved with the dialog?

**Comment by Euzee** [comment]
Yeah, sounds reasonable. I'll let you know when it will be ready.

**Comment by Euzee** [comment]
@luckcoolla 
Done. 
Check updated readme and use it with builder )

**Comment by luckcoolla** [comment]
Yep, now it's better.
Probably in future it will be possible to add different rationale messages for different permission requests.

Thank you @Euzee !
