### ISSUE TITLE
android:allowBackup

### ISSUE THREAD

**Issue by kolomboss** [Euzee/permissionUtil#6]
After add "implementation 'com.github.euzee:permissionUtil:1.0.5'" to build.gradle 
```
Error: Attribute application@allowBackup value=(true) from AndroidManifest.xml:34:9-35
	is also present at [com.github.euzee:permissionUtil:1.0.5] AndroidManifest.xml:13:9-36 value=(false).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:32:5-87:19 to override.
```

It have a suggestion, but i don`t want to do this (tools, replace and other not neccessary actions).
Can you do something? Remove "allowBackup" from manifest, or something?

**Comment by Euzee** [comment]
@kolomboss done
